Fix `TypeError: _CountedFileLock.__init__() got an unexpected keyword argument 'timeout'` (#345)
* Fix TypeError: _CountedFileLock.__init__() got an unexpected keyword argument 'timeout'

* fix

* fix type check

* ignore Skipping analyzing "virtualenv": module is installed, but missing library stubs or py.typed marker  [import-untyped]